spring:
  application:
    name: cvbuilder
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30m
      cache-null-values: false
      key-prefix: "cvbuilder:"
      use-key-prefix: true
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: cvbuilder
      auto-index-creation: true
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,email,profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
server:
  port: 8888

app:
  interview:
    blocks:
      - personalInfo
      - experience
      - education
      - skills
      - projects
      - languages
      - certificates