spring:
  application:
    name: cvbuilder
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30m
      cache-null-values: false
      key-prefix: "cvbuilder:"
      use-key-prefix: true
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: cvbuilder
      auto-index-creation: true
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
server:
  port: 8888

app:
  security:
    oauth2:
      enabled: true
  interview:
    blocks:
      - personalInfo
      - experience
      - education
      - skills
      - projects
      - languages
      - certificates